### PR TITLE
Fix to use Promise.all instead of async package

### PR DESCRIPTION
**Pull request by abetomo**
Reduce dependent packages.

### CODE REVIEW

**Comment by zeke** [comment]
This looks good to me. Older versions of Node.js don't have Promise support built in. That's fine though, we can just stop supporting those old versions. Can you add an `engines.node` semver range to package.json that sets it to the lowest compatible version of Node we want to support? Maybe like `>=6`?

**Comment by brodybits** [comment]
> Can you add an `engines.node` semver range to package.json that sets it to the lowest compatible version of Node we want to support? Maybe like `>=6`?

This should have been done *before* bumping to major version 5. May not be such a big issue if you guys do it now.

**Comment by abetomo** [comment]
Thank you for review!
`engines.node` updated.
It passes the test of Node.js6 and it is the oldest version in LTS.

**Comment by zeke** [comment]
```
~/git/zeke/standard-markdown master
$ np patch
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using npm
 ✔ Running tests
 ✔ Bumping version using npm
 ✔ Publishing package
 ✔ Pushing tags

 standard-markdown 5.0.1 published 🎉
```

**Pull request merged**
