### PR TITLE
Add a "pattern" and "ignore" option

### LINKED ISSUE #9: [Question] How to ignore selective files?
```bash
❯ standard-markdown
v8-tips/freeing-memory.md:11:5: 'foo' is already defined
workflow/scope.md:18:1: 'objt' is constant.
workflow/scope.md:18:1: 'objt' is constant.
workflow/scope.md:27:7: 'objt' is already defined
```

I want to ignore this files, but I don't want to use inline comment for do that. Could be possible providing a globby CLI pattern?

### PR DESCRIPTION
**Pull request by MarshallOfSound**
This allows more control over which files are actually linted

Fixes #9

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
To demonstrate how this works.

```bash
# Run the following in this repository
node cli.js
# Lints 4 files

node cli.js --pattern tests/**/*.md
# Lints 3 files

node cli.js --pattern **/*.md
# Lints 4 files

node cli.js --pattern **/*.md --ignore *.md
# Lints 3 files
```

**Comment by zeke** [comment]
Nice! Just needs some documentation.

So does `ignore` take precedence over `pattern` because it's declared after?

As an alternative, what about supporting (and documenting) a style where you can specify multiple patterns and no `ignore`?

```sh
node cli.js --pattern "tests/**/*.md,!*.md"
```

Or just allowing the patterns to be set without the `pattern` bit. This is more like how `standard` works:

```sh
node cli.js tests/**/*.md !*.md
```

cc @Kikobeats who originally requested the feature.

**Comment by Kikobeats** [comment]
wow, that's was quickly!

I'm agree with @zeke and standard-way approach; Just provide the glob pattern.

```
node cli.js tests/**/*.md !*.md
```

That's is more natural for specify globs; In addition the implementation need to handle less code.

**Comment by MarshallOfSound** [comment]
@zeke @Kikobeats 

Just updated to allow the following syntax

```bash
node cli.js tests/**/*.md !*.md
```

My example before would now look like this

```bash
# Run the following in this repository
node cli.js
# Lints 4 files

node cli.js tests/**/*.md
# Lints 3 files

node cli.js **/*.md
# Lints 4 files

node cli.js **/*.md !*.md
# Lints 3 files

# You can also still specify the CWD
node cli.js tests/fixtures *.md
# Lints 3 files
```

**Comment by zeke** [comment]
This means the `[cwd]` in USAGE is moot now, right?

```
❯ node cli.js --help

  Usage: cli [options] [cwd] [patterns...]

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
    -f, --fix      Attempt to fix basic standard JS issues
    -v, --verbose  Verbose mode
```

**Comment by MarshallOfSound** [comment]
@zeke I left it in there in case it had a valid use case.  Maybe something silly like

```bash
node cli.js ../electron/docs **/*.md
```

**Comment by zeke** [comment]
Trying this out locally, I'm hitting a few snags:

```sh
❯ node cli.js tests/**/*.md
/Users/zeke/zeke/standard-markdown/node_modules/glob/sync.js:325
        throw error
        ^

Error: ENOTDIR invalid cwd /Users/zeke/zeke/standard-markdown/tests/fixtures/clean.md
```

Wrapping the pattern in quotes seems to fix it:

```sh
node cli.js "tests/**/*.md"
# works
```

I think the issue is that the yargs `action` method is receiving an unexpected `cwdValue`. Some logging:

```
❯ node cli.js tests/**/*.md
cwdValue: tests/fixtures/clean.md
derived cwd: tests/fixtures/clean.md
```

**Comment by MarshallOfSound** [comment]
@zeke I can't replicate your `Error` issue, although I am on windows at the moment so maybe there is some path / cwd differences that I can't replicate currently.

**Comment by MarshallOfSound** [comment]
Interesting, I can replicate on linux. I'll investigate

**Comment by MarshallOfSound** [comment]
Ohhhhhhh, @zeke do you use ZSH like me?

**Comment by zeke** [comment]
> do you use ZSH

Yep

**Comment by MarshallOfSound** [comment]
To demonstrate the issue I just fixed @zeke.  Try running this command in bash and zsh.

```bash
node -e 'console.log(process.argv)' **/*.md
```

In bash it will log exactly what you expect.  In ZSH it automatically expands the glob so you get a list of files instead of the original glob

**Comment by zeke** [comment]
Looks good. Maybe just some examples with inclusion and exclusion patterns in the README?

**Comment by MarshallOfSound** [comment]
@zeke Added some examples 👍

**Comment by zeke** [comment]
✨ 2.2.0 ✨

**Pull request merged**
