### PR TITLE
Modify to follow the rules of the new 'standard'

### PR DESCRIPTION
**Pull request by abetomo**
I upgraded the package and
fixed it according to the latest 'standard' rules.

### CODE REVIEW

**Comment by abetomo** [comment]
The test fails in End-of-Life Node.js.
I opened a PR (#26) to update travis.yml.

**Comment by zeke** [comment]
Hey I've merged your other PRs. If you rebase this branch with master, it may fix the failing CI here.

Thanks for the updates!

**Comment by abetomo** [comment]
@zeke Thank you for review!
I rebased.

**Comment by zeke** [comment]
```
$ np major
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using npm
 ✔ Running tests
 ✔ Bumping version using npm
 ✔ Publishing package
 ✔ Pushing tags

 standard-markdown 5.0.0 published 🎉
```

**Comment by zeke** [comment]
Thanks, @abetomo 🤘

**Comment by abetomo** [comment]
Thank you for release!

**Pull request merged**
