### PR TITLE
removed lodash dep

### PR DESCRIPTION
**Pull request by jimmywarting**
- Removed unused lodash.range
- Replaced `lodash.flat` with `arr.flat` instead

### CODE REVIEW

**Review by zeke — COMMENTED** [review]
Nice! Cool to see that [Array.prototype.flat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) is a thing now. ✨ 

Does this mean `lodash.flatten` is not used anywhere? If so, can you remove it from the package.json file?

**Comment by zeke** [comment]
Looks like [Node.js 11 or greater](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#browser_compatibility) is required for `.flat()`. Can you also add an `engines.node: ">=11"` in package.json to make that more explicit?

**Comment by jimmywarting** [comment]
It was already removed from package.json 
Can add engines.node: ">=11" later today. Don't have a computer right now

**Comment by jimmywarting** [comment]
engines.node: ">=11" added

**Comment by zeke** [comment]
```
$ np minor --no-2fa

Publish a new version of standard-markdown (current: 7.0.0)

Commits:
- Merge pull request #41 from jimmywarting/rm-lodash.flatten  4cff1b3
- set engines.node to >=11  8404f63
- rm unused lodash range  cf0eeae
- removed lodash.flatten dep  7069af2

Commit Range:
v7.0.0...master

Registry:
https://registry.npmjs.org/


  ✔ Prerequisite check
  ✔ Git
  ✔ Cleanup
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✔ Bumping version using npm
  ✔ Publishing package using npm
  ✔ Pushing tags
  ✔ Creating release draft on GitHub

 standard-markdown 7.1.0 published 🎉
```

Thanks @jimmywarting!

**Pull request merged**
